# Generated by Django 3.0.3 on 2020-02-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200209_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='products',
            name='stock',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10000),
        ),
    ]
