# Generated by Django 3.0.3 on 2020-02-09 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200209_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='productss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=99999)),
                ('stock', models.DecimalField(decimal_places=0, default=1, max_digits=10000)),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=10000)),
                ('categories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.categories')),
            ],
        ),
    ]
