# Generated by Django 3.0.3 on 2020-02-09 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productss'),
    ]

    operations = [
        migrations.DeleteModel(
            name='productss',
        ),
    ]
